#!/bin/bash
#Yabai config
#layout
yabai -m config layout bsp

#Window placement
yabai -m config window_placement second_child

#padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

#mouse settings
#yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
#yabai -m window --focus mouse
#yabai -m config mouse_follows_focus on

#disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^ProtonVPN$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Whatsapp$" manage=off

#window opacity
#yabai -m config window_opacity on
#yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity 0.9

#borders
borders active_color=0xff7dc4e4 inactive_color=0xff7c69a2 width=6.0 hidpi=on

#sketchybar
yabai -m config external_bar all:43:0
